"""'initial'

Revision ID: e5330686771f
Revises: 
Create Date: 2024-09-22 08:32:51.472653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5330686771f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True, default=sa.text('now()')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentstext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id_doc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_doc'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentstext')
    op.drop_table('documents')
    # ### end Alembic commands ###
